# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: hanh9898
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hello_app_development

test:
  <<: *default
  database: hello_app_test

production:
  <<: *default
  database: sample_app_production
  username: sample_app
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>
