default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: hanh9898
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hello_app_development
  
test:
  <<: *default
  database: hello_app_test
  
production:
  <<: *default
  database: hello_app_production
  username: hello_app
  password: <%= ENV['hanh9898'] %>
